[window]
title = '最终幻想XIV' # 窗口标题

[fishing]
patience_timeout = 60 # 耐心持续时间（秒）

[fishing.key_binding]
cast = '1' # 抛竿 キャスティング
hook = '2' # 提钩 フッキング
patience = 'Q' # 耐心 ペーシェンス
precision_hookset = '3' # 精准提钩 プレシジョンフッキング
powerful_hookset = '4' # 强力提钩 ストロングフッキング
